# Generated by Django 5.2.4 on 2025-08-10 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_experience_years_driver_is_available_and_more'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='depature_time',
            new_name='departure_time',
        ),
        migrations.AddField(
            model_name='journey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_journeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_journeys', to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journey',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='rides.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.driver'),
        ),
    ]
