# Generated by Django 5.2.4 on 2025-08-10 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_experience_years_driver_is_available_and_more'),
        ('rides', '0004_alter_journey_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_journeys', to='accounts.driver'),
        ),
    ]
